use_frameworks!

platform :ios, '12.0'

target 'SuperTokensSession_Example' do
  pod 'SuperTokensIOS', :path => '../'

  target 'SuperTokensSession_Tests' do
    inherit! :search_paths

    
  end
end
