version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  deploy_gh_pages:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run: (cd website && npm i)
      - run: git config --global user.email "rishabh.poddar@gmail.com"
      - run: git config --global user.name "Rishabh Poddar"
      - run: ./publishToGit.sh
      - slack/status
workflows:
  version: 2
  tagged-build:
    jobs:
      - deploy_gh_pages:
          context:
            - slack-notification
          filters:
            branches:
              only: 
                - website