version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  slack: circleci/slack@3.4.2
  jq: circleci/jq@2.2.0
jobs:
  publish:
    macos:
      xcode: 14.1.0
    steps:
      - checkout
      - run: pod lib lint SuperTokensIOS.podspec
      - run: pod trunk push
      - slack/status
  test:
    macos:
      xcode: 14.1.0
    steps:
      - checkout
      - run:
          name: Generate config
          command: cd .circleci && ./generateConfig.sh
      - continuation/continue:
          configuration_path: .circleci/config_continue.yml
  update-docs:
    macos:
      xcode: 14.3.1
    steps:
      - checkout
      - run: cd ../ && git clone git@github.com:supertokens/supertokens-backend-website.git
      - run: gem install jazzy
      - run: jazzy --output ./docs --podspec SuperTokensIOS.podspec
      - run: (cd .circleci && ./updateDocsInWebsite)
      - slack/status

workflows:
  version: 2
  tagged-build:
    jobs:
      - publish:
          requires:
            - update-docs
          context:
            - slack-notification
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test:
          context:
            - slack-notification
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              only: /test-cicd\/.*/
      - update-docs:
          context:
              - slack-notification
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/