use_frameworks!

platform :ios, '13.0'

target 'SuperTokensSession_Example' do
  pod 'SuperTokensIOS', :path => '../../'

  target 'SuperTokensSession_Tests' do
    inherit! :search_paths

    
  end
end
